export const ADD_RECIPE = 'ADD_RECIPE'
export const ADD_RECIPE_INIT = 'ADD_RECIPE_INIT'
export const ADD_RECIPE_SUCCESS = 'ADD_RECIPE_SUCCESS'
export const ADD_RECIPE_FAIL = 'ADD_RECIPE_FAIL'

export const REMOVE_RECIPE = 'REMOVE_RECIPE'

export const FETCH_RECIPES = 'FETCH_RECIPES'
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS'
export const FETCH_RECIPES_FAIL = 'FETCH_RECIPES_FAIL'
export const FETCH_RECIPES_START = 'FETCH_RECIPES_START'

export const ADD_STAR = 'ADD_STAR'
export const REMOVE_STAR = 'REMOVE_STAR'